#!/usr/bin/env ruby
require_relative "input.rb"

FILES.each do |file|
  dropfile = File.join(ENV["HOME"],"Dropbox/images", File.basename(file))
  unless File.exists? dropfile
    puts "#{file} -> #{dropfile}"
    `convert "#{file}" -strip -resize 1024x "#{dropfile}"`
    `exiv2  -M"set Xmp.xmpRights.Marked True" \
      -M"set Xmp.xmpRights.UsageTerms 'This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License (http://creativecommons.org/licenses/by-sa/4.0/).'" \
      -M"set Xmp.dc.creator void@alfadeo.de" \
      -M"set Xmp.dc.rights 'This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License (http://creativecommons.org/licenses/by-sa/4.0/).'" \
      -M"set Xmp.dc.description Original artwork available from void@alfadeo.de" #{dropfile}`
  end
end

Dir[File.join(ENV["HOME"],"Dropbox/images", "*")].each do |dropfile|
  src = File.join(ENV["HOME"],"images", "art", File.basename(dropfile))
  puts `rm #{dropfile}` unless FILES.include? src
end
