#!/usr/bin/env ruby
require_relative 'model.rb'
require_relative 'gui.rb'

class ReviewGui < Gui
  def keyPressEvent event
    k = event.key
    t = event.text
    if k == Qt::Key_Insert
      @model[@model.current_idx].keep
      @model.images.delete_at @model.current_idx
    elsif k == Qt::Key_Delete
      @model[@model.current_idx].delete
      @model.images.delete_at @model.current_idx
    else
      super event
    end
    current_widget.redraw
  end
end

app = Qt::Application.new([])
model = Model.new ARGV
model.images.select!{|i| i.rating == 0}
v = ReviewGui.new model
app.exec
