#!/usr/bin/env ruby
require_relative 'model.rb'
require_relative 'gui.rb'

class SampleGui < Gui
  def keyPressEvent event
    case event.text
    when " ", "v"
      @model.current.play
    else
      super event
    end
  end
end

app = Qt::Application.new([])
model = Model.from_dir ARGV
v = SampleGui.new model
app.exec

